import { Inter } from "next/font/google";
import Header from "./Header/page";
import Navbar from "./Navbar/page";
import "./globals.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zaxbys home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
      <Header/>
      <Navbar/>
        {children}
   
      </body>
    </html>
  );
}
