import { Inter } from "next/font/google";
import Navbar from "./Navbar/page";
import "./globals.css";
import Conditionallayout from "./Conditionallayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zaxbys home",
  description: "Generated by create next app",
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Conditionallayout />
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
